apiVersion: v1
kind: Service
metadata:
  name: weather-memcache
  namespace: weather
  labels:
    app: weather-memcache
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
      name: memcache
  selector:
    app: weather-memcache
